/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Collection
 * Android class: COL_GlobalProcedures
 * Date: 21/11/2019 13:43:50
 * Version of wdjava64.dll: 24.0.254.7
 */


package com.mycompany.ts_broadcast.wdgen;


import com.mycompany.ts_broadcast.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.api.*;
/*Imports trouvés dans le code WL*/
import android.widget.Toast;
import android.app.Activity;
import android.support.annotation.Nullable;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.content.Context;
import android.content.ComponentName;
import android.content.IntentFilter;
import android.content.Intent;
import android.content.Context;
import android.content.BroadcastReceiver;
import android.widget.Toast;
import android.app.Activity;
import android.support.annotation.Nullable;
import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.content.Context;
import android.content.ComponentName;
/*Fin Imports trouvés dans le code WL*/



class GWDCPCOL_GlobalProcedures extends WDCollProcAndroid
{

public WDProjet getProjet()
{
return GWDPTS_Broadcast.getInstance();
}

public IWDEnsembleElement getEnsemble()
{
return GWDPTS_Broadcast.getInstance();
}

protected String getNomCollection()
{
return "COL_GlobalProcedures";
}
private final static GWDCPCOL_GlobalProcedures ms_instance = new GWDCPCOL_GlobalProcedures();
public final static GWDCPCOL_GlobalProcedures getInstance()
{
return ms_instance;
}

// Code de déclaration de COL_GlobalProcedures
static public void init()
{
ms_instance.initDeclarationCollection();

try
{
}
finally
{
finDeclarationCollection();
}

}




// Code de terminaison de COL_GlobalProcedures
static public void term()
{
ms_instance.initTerminaisonCollection();

try
{
}
finally
{
finTerminaisonCollection();
}

}



// Nombre de Procédures : 5

public static void ShopperCreate()
{
	boolean temp = false;
	Context context = getApplicationContext();
	Intent intent = new Intent();
	ComponentName cn = new ComponentName("com.touchsides.touchprovider","touchsides.com.registrations.RegisterUserActivity");
	
	intent.putExtra("Role", "Shopper");
	intent.putExtra("ByPassAuth", true);	
	intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
	
	try {
		intent.setComponent(cn);
		context.startActivity(intent);
	} catch (ActivityNotFoundException e) {
		cn = new ComponentName("com.touchsides.touchprovider.debug","touchsides.com.registrations.RegisterUserActivity");
		intent.setComponent(cn);
		context.startActivity(intent);
	} catch(Exception e){
		temp = callWLProcedure_boolean("NotifyUI","An error occured while creating the user.");
	}
}

public static void FindBroadCastReceiver()
{
	Context myContext = getApplicationContext();
	
	IntentFilter filter = new IntentFilter("touchsidesOdysseyAction");
	getCurrentActivity().registerReceiver(findShopper, filter);     
}

static BroadcastReceiver findShopper = new BroadcastReceiver(){
	public void onReceive(Context context, Intent intent){
		Context myContext = getApplicationContext();
		
		String shopperName = intent.getStringExtra("name");
		String shopperSurname = intent.getStringExtra("surname");
		String shopperGuid = intent.getStringExtra("guid");
		int shopperCashback = intent.getIntExtra("cashback",0);
		
		//set
		boolean result = false;
		result = callWLProcedure_boolean("SetFindResultData", shopperName, shopperSurname, shopperGuid, shopperCashback);
	}
};

public static void ShopperFind()
{
	//Get the required context
	Activity leActivity = getCurrentActivity();
	Context leContext = getApplicationContext();
	//implement findshopper and call find()
	FindShopperClass findShopper = new FindShopperClass();
	findShopper.find( );
}

public static class FindShopperClass extends Activity {	
	public void find()
	{		
		Activity activityContext = getCurrentActivity();
		try{
			Intent i = new Intent();
			ComponentName cn = new ComponentName("com.touchsides.touchprovider", "com.touchsides.till.shopper.FindShopperActivity");
			i.putExtra("ByPassAuth", true);
			i.setComponent(cn);
			activityContext.startActivityForResult(i, 10);		
		} catch(ActivityNotFoundException e) {
			Intent i = new Intent();
			ComponentName cn = new ComponentName("com.touchsides.touchprovider.debug", "com.touchsides.till.shopper.FindShopperActivity");
			i.setComponent(cn);
			i.putExtra("ByPassAuth", true);
			activityContext.startActivityForResult(i, 10);					
		}
	}
	
	@Override
	public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
		super.onActivityResult(requestCode, resultCode, data);		
	}
}
static public WDObjet fWD_setFindResultData( WDObjet vWD_sName , WDObjet vWD_sSurname , WDObjet vWD_sGuid , WDObjet vWD_nCashback )
{
ms_instance.initExecProcGlobale("SetFindResultData");

try
{
vWD_sName = WDParametre.traiterParametre(vWD_sName, 1, false, 16);

vWD_sSurname = WDParametre.traiterParametre(vWD_sSurname, 2, false, 16);

vWD_sGuid = WDParametre.traiterParametre(vWD_sGuid, 3, false, 16);

vWD_nCashback = WDParametre.traiterParametre(vWD_nCashback, 4, false, 8);


// WIN_Broadcasts.STC_Result = "Shopper Name: " + sName + Charact(10) + 
GWDPTS_Broadcast.getInstance().getWIN_Broadcasts().mWD_STC_Result.setValeur(new WDChaineU("Shopper Name: ").opPlus(vWD_sName).opPlus(WDAPIChaine.caract(10)).opPlus("Shopper Surname: ").opPlus(vWD_sSurname).opPlus(WDAPIChaine.caract(10)).opPlus("Shopper Guid: ").opPlus(vWD_sGuid).opPlus(WDAPIChaine.caract(10)).opPlus("Shopper Cashback: ").opPlus(vWD_nCashback));

// RESULT False
return new WDBooleen(false);

}
finally
{
finExecProcGlobale();
}

}


static public WDObjet fWD_notifyUI( WDObjet vWD_sMessage )
{
ms_instance.initExecProcGlobale("NotifyUI");

try
{
vWD_sMessage = WDParametre.traiterParametre(vWD_sMessage, 1, false, 16);


// Info(sMessage)
WDAPIDialogue.info(vWD_sMessage.getString());

// RESULT False
return new WDBooleen(false);

}
finally
{
finExecProcGlobale();
}

}



////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
