/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Projet
 * Android class: TS_Broadcast
 * Date: 26/11/2019 14:30:05
 * Version of wdjava64.dll: 24.0.254.7
 */


package com.mycompany.ts_broadcast.wdgen;


import com.mycompany.ts_broadcast.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/





public class GWDPTS_Broadcast extends WDProjet
{
/**
 * Accès au projet: TS_Broadcast
 * Pour accéder au projet à partir de n'importe où: 
 * GWDPTS_Broadcast.getInstance()
 */
public static GWDPTS_Broadcast getInstance()
{
return (GWDPTS_Broadcast) ms_instance;
}

 // WIN_Main
public GWDFWIN_Main mWD_WIN_Main = new GWDFWIN_Main();
 // accesseur de WIN_Main
public GWDFWIN_Main getWIN_Main()
{
mWD_WIN_Main.checkOuverture();
return mWD_WIN_Main;
}

 // WIN_Broadcasts
public GWDFWIN_Broadcasts mWD_WIN_Broadcasts = new GWDFWIN_Broadcasts();
 // accesseur de WIN_Broadcasts
public GWDFWIN_Broadcasts getWIN_Broadcasts()
{
mWD_WIN_Broadcasts.checkOuverture();
return mWD_WIN_Broadcasts;
}

 // WIN_NFC
public GWDFWIN_NFC mWD_WIN_NFC = new GWDFWIN_NFC();
 // accesseur de WIN_NFC
public GWDFWIN_NFC getWIN_NFC()
{
mWD_WIN_NFC.checkOuverture();
return mWD_WIN_NFC;
}


 // Constructeur de la classe GWDPTS_Broadcast
public GWDPTS_Broadcast()
{
// Définition des langues du projet
setLangueProjet(new int[] {2}, new int[] {0}, 2, false);
ajouterCollectionProcedures(GWDCPCOL_GlobalProcedures.getInstance());

// Palette des couleurs
setPaletteCouleurGabarit(new int[] {0x394AE1, 0x26A0FA, 0x6DBC61, 0x85A800, 0xD2AC54, 0xC9822B, 0xA95CF8, 0xB86592, 0xB74A5E, 0x654E44, 0xA5A595});
ajouterFenetre("WIN_Main", mWD_WIN_Main);
ajouterFenetre("WIN_Broadcasts", mWD_WIN_Broadcasts);
ajouterFenetre("WIN_NFC", mWD_WIN_NFC);



}


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
public String getVersionApplication(){ return "0.0.52.0";}
public String getNomSociete(){ return "Odyssey Software";}
public String getNomAPK(){ return "TS_Broadcast";}
public int getIdNomApplication(){return com.mycompany.ts_broadcast.R.string.app_name;}
public boolean isModeAnsi(){ return false;}
public boolean isAffectationTableauParCopie(){ return true;}
public boolean isAssistanceAutoHFActive(){ return true;}
public String getPackageRacine(){ return "com.mycompany.ts_broadcast";}
public int getIdIconeApplication(){ return com.mycompany.ts_broadcast.R.drawable.i_c_o_n_e________0;}
public int getInfoPlateforme(EWDInfoPlateforme info)
{
switch(info)
{
case DPI_ECRAN : return 160;
case HAUTEUR_BARRE_SYSTEME : return 25;
case HAUTEUR_BARRE_TITRE : return 25;
case HAUTEUR_ACTION_BAR : return 48;
case HAUTEUR_BARRE_BAS : return 0;
case HAUTEUR_ECRAN : return 480;
case LARGEUR_ECRAN : return 320;
default : return 0;
}
}
public boolean isActiveThemeMaterialDesign()
{
return true;
}
////////////////////////////////////////////////////////////////////////////
public String getAdresseEmail() 
{
return "";
}
public boolean isIgnoreErreurCertificatHTTPS()
{
return false;
}
////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}
public String getNomProjet()
{
return "TS_Broadcast";
}
public String getNomConfiguration()
{
return "Android application";
}
public String getNomAnalyse()
{
return "";
}
public String getMotDePasseAnalyse()
{
return "";
}
public boolean isModeGestionFichierMultiUtilisateur()
{
return true;
}
public boolean isCreationAutoFichierDonnees()
{
return true;
}

////////////////////////////////////////////////////////////////////////////
// Formats des masques du projet
////////////////////////////////////////////////////////////////////////////
public String getFichierWDM()
{
return null;
}
protected void declarerRessources()
{
super.ajouterFichierAssocie("C:\\MY MOBILE PROJECTS\\TS_BROADCAST\\TEMPLATES\\WM\\210 MATERIAL DESIGN BLUE GREY\\MATERIAL DESIGN BLUE GREY_BTN_STD.PNG?E5_3NP_10_10_10_10",com.mycompany.ts_broadcast.R.drawable.material_design_blue_grey_btn_std_1_np3_10_10_10_10_selector, "");
}
// Initialisation des collections de procédures
public void initCollections()
{
GWDCPCOL_GlobalProcedures.init();

}


// Terminaison des collections de procédures
public void terminaisonCollections()
{
GWDCPCOL_GlobalProcedures.term();

}

/**
 * Lancer de l'application Android
 */
public static class WDLanceur extends WDAbstractLanceur
{
public Class<? extends WDProjet> getClasseProjet()
{
return GWDPTS_Broadcast.class;
}
}
}
