/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Splash Screen
 * Android class: TS_Broadcast
 * Date: 09/12/2019 09:11:17
 * Version of wdjava64.dll: 24.0.254.7
 */


package com.mycompany.ts_broadcast.wdgen;


import com.mycompany.ts_broadcast.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.ui.style.degrade.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class WDSplashScreenGen implements IWDSplashScreen
{
public int getIdImageFond(){return 0;}
public int getModeAffichageImageFond(){return 0;}
public int getIdNomApplication(){return com.mycompany.ts_broadcast.R.string.splashscreen_title;}
public int getIdInfoVersion(){return 0;}
public int getIdLogo(){return 0;}
public boolean isAvecAnimationChargement(){return false;}
public int getIdMessageChargement(){return 0;}
public int getCouleurLibelle(){return 0xFFFFFF;}
public IWDDegrade getFondDegrade(){return null;}
public int getCouleurFond(){return 0x383226;}
}
